### ISSUE TITLE
ls displays class

### ISSUE THREAD

**Issue by smudgegame** [ManApart/quest-command#21]
![image](https://user-images.githubusercontent.com/17369451/168407032-0ee8ce24-800a-416a-b29b-fc3b91a7a18c.png)

**Comment by ManApart** [comment]
This is a combination of two bugs, one is that after killing the farmer you were still in a battle and two is that the battle description was printing the full creature instead of the name.

**Comment by ManApart** [comment]
Killing the framer myself, I see that look properly moves back out of battle mode, so I'm not sure if the look bug was caused by the server or something else.
