### ISSUE TITLE
Commands overwritten when event occurs

### ISSUE THREAD

**Issue by smudgegame** [ManApart/quest-command#22]
![image](https://user-images.githubusercontent.com/17369451/168407132-ddac0bf2-fe42-47b1-9d96-7b8171a8f501.png)

**Comment by ManApart** [comment]
Thanks for the screenshot!

I don't think this is an easy fix as I think it's dependant on your terminal / client and that I can't do anything about it other than maybe clear and replay the text through client specific code? I agree it's a pain though.

One possible workaround is to use the debug command to turn off polling, but that's probably not worth it.

**Comment by ManApart** [comment]
I'm going to close this now as a "will not fix" but would love to fix it if someone can come up with a solution.
